# Generated by Django 4.1.7 on 2023-03-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_user_address_contact_number_user_address_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='contact_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
