# Generated by Django 4.1.7 on 2023-03-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_brand', '0003_alter_brand_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
