# Generated by Django 4.1.7 on 2023-03-22 12:20

import admin_brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_brand', '0006_alter_brand_brand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.PositiveIntegerField(default=admin_brand.models.generate_id, unique=True),
        ),
    ]
