# Generated by Django 4.1.7 on 2023-03-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cart_coupon_discount_alter_cart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon_discount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
