# Generated by Django 4.1.7 on 2023-03-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
