# Generated by Django 4.1.7 on 2023-03-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_variant', '0002_variant_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant_images',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_variant.product_variant'),
        ),
    ]
