# Generated by Django 4.1.7 on 2023-03-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_variant', '0003_alter_variant_images_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='variant_thumbnail'),
        ),
    ]
