# Generated by Django 4.1.7 on 2023-03-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_variant', '0004_product_variant_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('min_amount', models.PositiveBigIntegerField()),
                ('off_precent', models.PositiveIntegerField()),
                ('max_discount', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
    ]
