# Generated by Django 4.1.7 on 2023-03-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_variant', '0006_alter_coupon_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='off_precent',
            new_name='off_percent',
        ),
    ]
