# Generated by Django 4.1.7 on 2023-03-19 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_variant', '0007_rename_off_precent_coupon_off_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 29, 12, 47, 20, 728353, tzinfo=datetime.timezone.utc)),
        ),
    ]
