# Generated by Django 4.1.7 on 2023-03-19 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_variant', '0008_alter_coupon_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 29, 12, 48, 38, 417713, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
