# Generated by Django 4.1.7 on 2023-03-19 12:54

import admin_variant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_variant', '0010_alter_coupon_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(validators=[admin_variant.models.validate_expiry_date]),
        ),
    ]
