# Generated by Django 4.1.7 on 2023-03-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_variant', '0012_coupon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_available',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
