# Generated by Django 4.1.7 on 2023-03-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_variant', '0013_coupon_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_available',
        ),
    ]
